version: "3.7"

services:
  playkube:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CONFIG_MAP=some config
      - SECRET=some secret
      - PLAY_SECRET_KEY=9ac35bbfa6568318d1f0349e21388d4e7b30310b8806c5ff3cac61312a578120
    container_name: playkube
    ports:
      - "9000:9000"
    volumes:
        - conf_dir:/app/conf

volumes:
  conf_dir: {}
