apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: playkube
  name: playkube
spec:
  type: LoadBalancer
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
      nodePort: 31001
  selector:
    io.kompose.service: playkube
status:
  loadBalancer: {}
