apiVersion: v1
kind: Service
metadata:
  name: playkube
spec:
  type: LoadBalancer
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
      nodePort: 31001
  selector:
    app: playkube
