version: "3.7"

services:
  playkube:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CONFIG_MAP=some config
      - SECRET=some secret
      - PLAY_SECRET_KEY={{ play_secret }}
    container_name: playkube
    ports:
      - "9000:9000"
    volumes:
        - conf_dir:/app/conf

volumes:
  conf_dir: {}
